### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'p2g_18546/diamond.matches.tab'

### ISSUE THREAD

**Issue by sophietandonnet** [reslp/funannotate-docker#2]
Hello,

I am trying to run funannotate (version 1.7.4) through docker on a CentOS Linux 7. I get the following error:
"IOError: [Errno 2] No such file or directory: 'p2g_18546/diamond.matches.tab"

```
docker run --rm -it -v $(pwd):/data reslp/funannotate:1.7.4 predict -i JU1783-k35_Gapclosed_v1.fa.masked.cleanfun.sorted --species "Rhabditis sp. JU1783" --transcript_evidence Trinity.fasta.clean --rna_bam JU1783-RNA-reads-aln-sortedgenome.bam --protein_evidence metazoa-and-Arh-proteins.fasta --pasa_gff sample_mydb_pasa.sqlite.valid_gmap_alignments.gff3 --organism other --ploidy 2  --busco_db nematoda --strain JU1783 -o JU1783-funannotate1
-------------------------------------------------------
[01:04 PM]: OS: linux2, 24 cores, ~ 132 GB RAM. Python: 2.7.17
[01:04 PM]: Running funannotate v1.7.4
[01:04 PM]: Parsed training data, run ab-initio gene predictors as follows:
  Program        Training-Method
  augustus       pasa
  codingquarry   rna-bam
  glimmerhmm     pasa
  snap           pasa
[01:04 PM]: Loading genome assembly and parsing soft-masked repetitive sequences
[01:04 PM]: Genome loaded: 3,083 scaffolds; 58,291,147 bp; 17.03% repeats masked
[01:04 PM]: Existing transcript alignments found: JU1783-funannotate1/predict_misc/transcript_alignments.gff3
[01:04 PM]: Existing RNA-seq BAM hints found: JU1783-funannotate1/predict_misc/hints.BAM.gff
[01:07 PM]: Mapping 8,255,650 proteins to genome using diamond and exonerate
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/funannotate/aux_scripts/funannotate-p2g.py", line 266, in <module>
    Hits = parseDiamond(BlastResult)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/aux_scripts/funannotate-p2g.py", line 107, in parseDiamond
    with open(blastresult, 'rU') as input:
IOError: [Errno 2] No such file or directory: 'p2g_18546/diamond.matches.tab'
Traceback (most recent call last):
  File "/usr/local/bin/funannotate", line 660, in <module>
    main()
  File "/usr/local/bin/funannotate", line 650, in main
    mod.main(arguments)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/predict.py", line 951, in main
    lib.exonerate2hints(Exonerate, hintsP)
  File "/usr/local/lib/python2.7/dist-packages/funannotate/library.py", line 3315, in exonerate2hints
    with open(file, 'r') as input:
IOError: [Errno 2] No such file or directory: '/data/JU1783-funannotate1/predict_misc/protein_alignments.gff3'
```

Do you have any suggestions on how to fix this?

I have run the following commands (no errors) before running into the problem:

```
docker pull reslp/funannotate:1.7.4

docker run --rm -it -v /local/path/to/data/database:/data/database reslp/funannotate:1.7.4 setup -b nematoda

docker run --rm -it -v $(pwd):/data reslp/funannotate:1.7.4 clean -i /data/JU1783-k35_Gapclosed_v1.fa.masked -o /data/JU1783-k35_Gapclosed_v1.fa.masked.cleanfun

docker run --rm -it -v $(pwd):/data reslp/funannotate:1.7.4 sort -i /data/JU1783-k35_Gapclosed_v1.fa.masked.cleanfun -o /data/JU1783-k35_Gapclosed_v1.fa.masked.cleanfun.sorted

```

Any suggestion welcome! 
Thanks,
Sophie

**Comment by reslp** [comment]
Hi Sophie,

Looks like something is wrong with the paths (and maybe also the funannotate database). Does it work if you specify the full path to the output directory? Also I would specify the path to the funannotate database as a seperate bindpoint (the real path to the funannotate database needs to be changed).

Does this work?
```
docker run --rm -it -v /local/path/to/database:/data/database -v $(pwd):/data reslp/funannotate:1.7.4 predict -i JU1783-k35_Gapclosed_v1.fa.masked.cleanfun.sorted --species "Rhabditis sp. JU1783" --transcript_evidence Trinity.fasta.clean --rna_bam JU1783-RNA-reads-aln-sortedgenome.bam --protein_evidence metazoa-and-Arh-proteins.fasta --pasa_gff sample_mydb_pasa.sqlite.valid_gmap_alignments.gff3 --organism other --ploidy 2  --busco_db nematoda --strain JU1783 -o /data/JU1783-funannotate1
```

cheers,

Philipp

**Comment by sophietandonnet** [comment]
Dear Philipp,

Thanks for your quick response and sorry for taking so long to answer.

Our server has had some serious hardware problems and I haven't yet been
able to try your suggestions yet.
As soon as everything is back to normal I will come back to running
funannotate.

Thanks again!!
Sophie

Em ter., 9 de fev. de 2021 às 07:40, Philipp Resl <notifications@github.com>
escreveu:
