### ISSUE TITLE
error: ete3 not installed

### ISSUE THREAD

**Issue by Xueliang24** [reslp/funannotate-docker#3]
I use singularity to install funannotate by
`singularity pull docker://reslp/funannotate:1.8.1`

When funannotate check --show-versions, it showed 
Traceback (most recent call last):
  File "/usr/local/bin/ete3", line 6, in <module>
    from ete3.tools.ete import main
  File "/usr/local/lib/python3.7/dist-packages/ete3/tools/ete.py", line 55, in <module>
    from . import (ete_split, ete_expand, ete_annotate, ete_ncbiquery, ete_view,
  File "/usr/local/lib/python3.7/dist-packages/ete3/tools/ete_view.py", line 48, in <module>
    from .. import (Tree, PhyloTree, TextFace, RectFace, faces, TreeStyle, CircleFace, AttrFace,
ImportError: cannot import name 'TextFace' from 'ete3' (/usr/local/lib/python3.7/dist-packages/ete3/__init__.py)

even I install ete3 by pip and set environmental PATH, it also happened.

**Comment by reslp** [comment]
Hi,

thank you for using this container! The issue with `ete3` in `funannotate` is known for some time:

https://github.com/nextgenusfs/funannotate/issues/249
https://github.com/etetoolkit/ete/issues/195

there are some workarounds for this (one solution is explained in the first link), however it still can cause problems. Maybe this is what you already tried. In general most of funannotate should work fine though even without ete3. If I recall correctly, `ete3` is only used for one specific thing during` funannotate compare`. 

In general I would recommend to use a newer version of funannotate (a lot has changed since v1.8.1) and some other things like access to several annotation databases may not work anymore in older versions.

all the best,

Philipp

**Comment by Xueliang24** [comment]
Thanks for your quick response！
Because I met a problem when I wanna install funannotate by conda. The **augustus compilation error** could not be solved. 
So I wanna to use funannotate by singularity.
May I use `singularity pull docker://reslp/funannotate:lastest` to use newer version？

**Comment by reslp** [comment]
Yes, you well get a more up to date version. `singularity pull docker://reslp/funannotate:lastest` should give you 1.8.7 for example. However 1.8.11 is the most recent version (for which I do not have a container yet). But official funannotate also offers containers, you can check out the funannotate Github page for more info on that.

**Comment by Xueliang24** [comment]
Oh！Thanks

**Comment by Xueliang24** [comment]
Could you guide me how to set the PATH of gmes_petal.pl or GENEMARK in the sandbox built from funannotate lastest?
Now I set `export GENEMARK_PATH="${GENEMARK_PATH:-"/venv/opt/gmes_petap"}"` in the /.singularity.d/env/10-docker2singularity.sh.
Meanwhile I set echo `"export GENEMARK_PATH=/venv/opt/gmes_petap" >/venv/etc/conda/activate.d/gmes_petap.sh` and `echo "unset GENEMARK_PATH" >/venv/etc/conda/deactivate.d/gmes_petap.sh`.
Also, I used `chmod -R 777` GENEMARK software and `perl change_path_in_perl_scripts.pl "/venv/bin/perl"` according to the `which perl`. 
But it still failed.

**Comment by Xueliang24** [comment]
What the author said in the[nextgenusfs/funannotate/issues/687]( https://github.com/nextgenusfs/funannotate/issues/687#issuecomment-1022877196) might be right.
Emm. I run `funannotate test -t predict --cpus 10` and it was successful. So likely the funannotate check is just not accurate in this case because it isn't looking at the ENV variables

**Comment by reslp** [comment]
The PATH should already be set inside the container, so there is nothing you should have to do there. Try running ``env`` inside the container to see all the variables. To make Genemark work, you have to follow the instructions in the [README](https://github.com/reslp/funannotate-docker/blob/master/README.md) file. This is necessary because GENMARK_PATH is set to a predefined variable. However, you can also run funannotate without GeneMark, if it is not there funannotate should realize and not use it to predict genes.
